# Generated by Django 2.2.7 on 2020-01-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberofData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.IntegerField()),
                ('login', models.IntegerField()),
                ('users', models.CharField(max_length=50)),
            ],
        ),
    ]
