# Generated by Django 2.2.7 on 2020-01-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_p_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='p_image',
            new_name='image',
        ),
    ]
